feat(LT-5671): Axle: add new socket method to remove on behalf state
LykkeBusiness/axle pull request #113
Opened 2024-08-20 10:36 UTC by lykke-vashetsin

2024-11-06 13:20 UTC, tarurar requested changes

2024-11-06 13:20 UTC, tarurar commented on src/Axle/Hubs/SessionHub.cs
> +        public Task<bool> SetOffBehalfAccount(string accountId)
```suggestion
        public Task<bool> SetOffOnBehalfAccount(string accountId)
```

2024-11-06 13:20 UTC, tarurar commented on src/Axle/Services/SessionService.cs
> +                await sessionRepository.Remove(sessionId, session.UserName, session.AccountId);
Don't you need to cover with lock only data modification (remove method)?

2024-12-04 10:45 UTC, lykke-vashetsin commented on src/Axle/Hubs/SessionHub.cs
> +        public Task<bool> SetOffBehalfAccount(string accountId)
done

2024-12-04 10:45 UTC, lykke-vashetsin commented on src/Axle/Services/SessionService.cs
> +                await sessionRepository.Remove(sessionId, session.UserName, session.AccountId);
removed lock completely

2024-12-16 11:59 UTC, tarurar approved these changes

2024-12-16 12:12 UTC, merged